trigger:
  - master

pool: Default

steps:
  - script: python3 -m pip install -r requirements.txt --user
    displayName: Install Requirements
  - script: python3 -m pytest --cov tests --junit-xml junit.xml tests
    displayName: Collect Coverage
  - script: python3 -m coverage xml
    displayName: Generate Coverage Report
  - task: PublishTestResults@2
    displayName: Publish Test Results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: junit.xml
  - task: PublishCodeCoverageResults@1
    condition: succeededOrFailed()
    displayName: Publish Coverage Report
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: coverage.xml
